version: 2
updates:
  # npm (JavaScript) の依存関係
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "フロントエンドアプリケーション"

  # gradle (Java) の依存関係
  - package-ecosystem: "gradle"
    directory: "/backend/"
    schedule:
      interval: "weekly"
    labels:
      - "gradle"
      - "バックエンドアプリケーション"

  # GitHub Actions の依存関係
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      - "CI/CD"
