version: 2
updates:
  # npm (JavaScript) の依存関係
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "フロントエンドアプリケーション"
    open-pull-requests-limit: 10

  # gradle (Java) の依存関係
  - package-ecosystem: "gradle"
    directory: "/backend/"
    schedule:
      interval: "weekly"
    labels:
      - "gradle"
      - "バックエンドアプリケーション"
    open-pull-requests-limit: 10

  # GitHub Actions の依存関係
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      - "CI/CD"
    open-pull-requests-limit: 10
