-- ユーザーロールのテーブル定義
DROP TABLE IF EXISTS ROLES CASCADE;
CREATE TABLE ROLES
(
  ID SERIAL NOT NULL PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL UNIQUE
);

-- 認証情報のテーブル定義
DROP TABLE IF EXISTS AUTHES CASCADE;
CREATE TABLE AUTHES
(
  ID VARCHAR(64) NOT NULL PRIMARY KEY,
  PASSWORD_HASH VARCHAR(64) NOT NULL,
  ROLE_ID SERIAL NOT NULL REFERENCES ROLES(ID),
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE
);

-- ユーザーのテーブル定義
DROP TABLE IF EXISTS USERS CASCADE;
CREATE TABLE USERS
(
  ID BIGSERIAL NOT NULL PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
  AUTH_ID VARCHAR(64) NOT NULL REFERENCES AUTHES(ID) ON DELETE CASCADE
);

-- 日記のテーブル定義
DROP TABLE IF EXISTS DIARIES CASCADE;
CREATE TABLE DIARIES
(
  ID BIGSERIAL NOT NULL PRIMARY KEY,
  TITLE VARCHAR(64) NOT NULL,
  CONTENT TEXT NOT NULL,
  CREATED_DATE TIMESTAMP NOT NULL,
  IS_DELETED BOOLEAN NOT NULL,
  USER_ID BIGSERIAL NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE
);